# This dictionary maps the string index from Blynk to a tuple
# containing the channel's name and its URL.
# The key ("0", "1", etc.) MUST match the value sent by the Blynk enum.
channels = {
    "1": ("Yle TV1", "https://yletv.akamaized.net/hls/live/622365/yletv1fin/playlist.m3u8"),
    "2": ("Yle TV2", "https://yletv.akamaized.net/hls/live/622366/yletv2fin/playlist.m3u8"),
    "3": ("MTV3", "https://live-fi.tvkaista.net/mtv3/live.m3u8"),
    "4": ("Nelonen", "https://live-fi.tvkaista.net/nelonen/live.m3u8"),
    "5": ("Yle Teema & Fem", "https://yletv.akamaized.net/hls/live/622367/yletvteemafemfin/playlist.m3u8"),
    "6": ("MTV Sub", "https://live-fi.tvkaista.net/sub/live.m3u8"),
#    "7": ("TV5", None),
    "8": ("Liv", "https://live-fi.tvkaista.net/liv/live.m3u8?hd=true"),
#    "9": ("Jim", "https://live-fi.tvkaista.net/jim/live.m3u8?hd=true"),
#    "10": ("Kutonen", None),
#    "11": ("TLC", None),
#    "12": ("Star Channel", None),
    "13": ("MTV Ava", "https://live-fi.tvkaista.net/ava/live.m3u8"),
    "14": ("Hero", "https://live-fi.tvkaista.net/hero/live.m3u8?hd=true"),
    "15": ("Frii", "https://live-fi.tvkaista.net/frii/live.m3u8"),
    "16": ("National Geographic", "https://live-fi.tvkaista.net/national-geographic/live.m3u8?hd=true"),
    "17": ("Eveo", "https://live-fi.tvkaista.net/tapahtumatv-eveo/live.m3u8?hd=true"),
#    "96": ("IskelmäTV", "https://mobiili.livetv.fi/memfs/f1819b9e-90da-408a-9a71-5c54e0cb5c33.m3u8"),
    "97": ("Järviradio", "https://streamer.radiotaajuus.fi/memfs/47f113bf-04ea-493b-a9d4-52945fd9db31.m3u8"),
    "98": ("MTV Uutiset", "https://live.streaming.a2d.tv/asset/20025962.isml/.m3u8"),
#    "99": ("YleX", "https://ylestudiolive.akamaized.net/hls/live/2007826/ylestudiolive-YleX/master.m3u8")
    "24": ("Lumiukko", "src/Assets/Videos/Lumiukko.mkv"),
    "25": ("Jouluradio", "https://ms-live-jouluradio01.nm-elemental.nelonenmedia.fi/master.m3u8"),
    "26": ("Julradio", "https://ms-live-jouluradio02.nm-elemental.nelonenmedia.fi/master.m3u8"),
    "27": ("Kauneimmat Joululaulut", "https://ms-live-jouluradio03.nm-elemental.nelonenmedia.fi/master.m3u8"),
    "28": ("Lasten Jouluradio", "https://ms-live-jouluradio04.nm-elemental.nelonenmedia.fi/master.m3u8"),
    "29": ("PopJoulu", "https://ms-live-jouluradio05.nm-elemental.nelonenmedia.fi/master.m3u8"),
    "30": ("Rouhea Joulu", "https://ms-live-jouluradio06.nm-elemental.nelonenmedia.fi/master.m3u8"),
    "31": ("Klassinen Joulu", "https://ms-live-jouluradio07.nm-elemental.nelonenmedia.fi/master.m3u8"),
    "32": ("Happy Holidays", "https://ms-live-jouluradio08.nm-elemental.nelonenmedia.fi/master.m3u8"),
}
